# Generated by Django 4.2.15 on 2024-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0003_category_routines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='routines',
            options={'verbose_name_plural': 'routines'},
        ),
        migrations.AlterField(
            model_name='routines',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
