# Generated by Django 4.2.15 on 2024-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0005_workout_workoutexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
