# Generated by Django 5.1 on 2024-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0006_workout_workoutexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='routines',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routines',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
