# Generated by Django 4.2.15 on 2024-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0008_workoutprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutprogress',
            name='total_reps',
        ),
        migrations.RemoveField(
            model_name='workoutprogress',
            name='total_sets',
        ),
        migrations.RemoveField(
            model_name='workoutprogress',
            name='total_weight',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
