# Generated by Django 4.2.15 on 2024-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0009_remove_workoutprogress_total_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutprogress',
            name='total_reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutprogress',
            name='total_sets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutprogress',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
