# Generated by Django 4.2.15 on 2024-09-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0010_remove_workoutexercise_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogress',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='gymmy.workoutexercise'),
        ),
    ]
