# Generated by Django 4.2.15 on 2024-09-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0012_routines_popularity_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogress',
            name='single_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
