# Generated by Django 4.2.15 on 2024-09-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0014_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogress',
            name='single_reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
