# Generated by Django 4.2.15 on 2024-10-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymmy', '0015_workoutprogress_single_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routines',
            name='favorites',
        ),
    ]
